### ISSUE TITLE
小米自带浏览器 Video DOM 层级问题

### ISSUE THREAD

**Issue by l19861225q** [Chimeejs/chimee-mobile-player#1]
RT，video DOM 始终处于最高级，z-index 不起作用，导致自定义的其他 DOM 元素被遮挡，有什么办法呢？已经设置了 `playsInline: true` 还是不行 ...

**Comment by yandeqiang** [comment]
这个问题，确实目前我这没有好的解决方案。 这个是浏览器的行为。 强制使用他的播放器。方便他插广告。

**Comment by yandeqiang** [comment]
什么型号的手机， 我在做黑名单😂， 方便把 ua 发一下吗？

**Comment by l19861225q** [comment]
手机名称：红米手机
手机型号：Redmi 4X
Android 版本：6.0.1 MMB29M
浏览器UA：Mozilla/5.0 (Linux; U; Android 6.0.1; zh-cn; Redmi 4X Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.146 Mobile Safari/537.36 XiaoMi/MiuiBrowser/9.3.10
