### ISSUE TITLE
请问播放器的控制条按钮如何绑定自定义事件？

### ISSUE THREAD

**Issue by chinabattlehawk** [Chimeejs/chimee-mobile-player#10]
如题，顺便说一下，需要自定义事件是因为在手机web页面点击全屏播放后，视频不会自动横屏，还是小小的，只是上下黑背景填充了屏幕，播放画面还是在中间。所以打算点击全屏切换按钮，做一些别的操作。
望速速指教，多谢多谢！

**Comment by yandeqiang** [comment]
你是要针对 screen 这个小组件自定义事件吗？ 如果是的，可以添加 events 事件， https://github.com/Chimeejs/chimee-plugin-mobile-controlbar

不过，全屏这个问题， 可以监听 player.$watch('isFullscreen', cb);

**Comment by chinabattlehawk** [comment]
你好，谢谢解答！我使用的是 chimee-mobile-player，这个插件是集成了 chimee-plugin-mobile-controlbar 的吧？如果要添加事件，需要再次引用 controlbar 插件吗？还是直接在播放器配置代码里添加 events 事件？

**Comment by yandeqiang** [comment]
可以参考这个 https://github.com/Chimeejs/chimee-plugin-mobile-controlbar/blob/master/demo/index.html

**Comment by chinabattlehawk** [comment]
你好，引用 chimee-mobile-player.browser.js 无法执行 new VConsole()，也无法执行 Chimee.install(chimeePluginMobileControlbar)。监听 player.$watch('isFullscreen', cb) 浏览器报错element[this._openKey] is not a function。请问这是怎么回事啊？

**Comment by yandeqiang** [comment]
是 chimee-mobile-player.browser.js 报错了吗？ ChimeeMobilePlayer 有这个对象吗？  具体错误看看？ 看看代码？

**Comment by chinabattlehawk** [comment]
//播放器命名空间
	var oVideoObj = {
		videoConfig: {
			wrapper: '#video', //播放器目标容器
			src: 'images/logo.mp4', //初始播放地址
			poster: 'images/bg_01.jpg', //初始封面
			autoplay: true, //自动播放
			controls: true, //播放控件
			playsInline: true, //是否内联
			preload: true, //自动加载
			x5VideoPlayerFullscreen: true,
			x5VideoOrientation: true,
			xWebkitAirplay: true,
			muted: false //是否静音
		},
		videoLive: 'images/logo.mp4',
		videoList: [],
		videoErrImg: document.getElementsByClassName('u-err-img')[0],
		videoPause: function () {
			oPlayer.pause();
		},
		videoPlay: function () {
			oPlayer.play();
		}
	};

	//载入播放器实例
	var oPlayer = new ChimeeMobilePlayer(oVideoObj.videoConfig); //正常

	oPlayer.$watch('isFullscreen', function () {
		console.log('ok');
	});
	// 浏览器报错
        // 点击全屏
        // TypeError: element[this._openKey] is not a function[详细了解] chimee-mobile-player.browser.js:7273:9
        // 点击取消全屏
	// TypeError: this.watch_screen is not a function[详细了解]  chimee-mobile-player.browser.js:12661:9

**Comment by yandeqiang** [comment]
配置看起来是没有问题， 
http://draft.yandeqiang.com/chimee-mobile-player/demo/ 看看 这个， 
你的版本是多少？

**Comment by chinabattlehawk** [comment]
chimee-mobile-player.browser.js
/** ChimeeMobilePlayer
 * chimee-mobile-player v0.0.2
 * (c) 2017 yandeqiang
 * Released under MIT
 */

**Comment by yandeqiang** [comment]
先升级一下吧。 估计是好久之前写的 bug🤦‍♂️

**Comment by chinabattlehawk** [comment]
你好，升级版本后，监听全屏事件以及给全屏按钮添加自定义事件都可以正常使用了。但是在火狐浏览器调试时，点击视频时会报错：
TypeError: evt.path is undefined[详细了解] chimee-mobile-player.browser.js:12142:1
然后还想请问一下，如何关掉按钮的默认功能，例如全屏按钮，点击不执行全屏操作，而通过自定义的事件，用别的方法实现全屏，比如旋转播放器盒子。
做的这个 Web 页面要嵌入到一个 app（安卓和 iOS 版本都有）中，但是点击全屏后，无法真正的全屏，视频上下是黑色，大小跟全屏前也没什么变化，不能旋转铺满整个屏幕。请问有什么办法实现真●全屏吗？

**Comment by toxic-johann** [comment]
可以尝试调整 [esFullscreen 中的 usestylefirst 字段](https://github.com/toxic-johann/es-fullscreen#usestylefirst)。从而使用 css 全屏。

具体 demo 需要参考一下 https://github.com/toxic-johann/es-fullscreen/blob/master/demo/base/index.js#L26

@yandeqiang 可以看看我们是否需要将这个选项开放出来。
