### ISSUE TITLE
 因为项目是采用传统的方式，没有es6没有工程化的，引入browe.js会报错

### ISSUE THREAD

**Issue by acegank** [Chimeejs/chimee-mobile-player#11]
error：ChimeeMobilePlayer is not defined

**Comment by toxic-johann** [comment]
引入的版本是？

**Comment by acegank** [comment]
从githut下的lib下的 chimee-mobile-player v0.1.6

**Comment by yandeqiang** [comment]
现在最新 0.1.7 先升级下试试。

**Comment by acegank** [comment]
你好，我下了最新的0.1.7版本，直接引入还是报错，ChimeeMobilePlayer is not defined

**Comment by acegank** [comment]
不好意思，是我搞错了，可以了，感谢！
