### ISSUE TITLE
播放进度条的问题以及播放对象的重置问题

### ISSUE THREAD

**Issue by chinabattlehawk** [Chimeejs/chimee-mobile-player#12]
播放过程中，跳转播放后，继续播放直到视频结束，进度条不会动。
![image](https://user-images.githubusercontent.com/29477870/37885614-cb18fece-30e8-11e8-9fff-74ff0a46b468.png)
另外，直接更改播放器的 src 地址和重新加载新的播放器时改变 src 地址，有什么区别？

**Comment by yandeqiang** [comment]
@toxic-johann 阿恒， 帮忙解释下第二个问题。

**Comment by toxic-johann** [comment]
> 重新加载新的播放器时改变 src 地址

这个方式是指？

**Comment by chinabattlehawk** [comment]
这样：
btn.onclick = function(){
  player.src = 'xxx.mp4';
  player.play();
}
这是 demo 里的方式，函数中将 player 使用更改后的配置重新 new 出来。
btn.onclick = reBuildPlayer(src,...);

第一种方式也能更改播放地址，但是会有什么隐患吗？
