### ISSUE TITLE
直播模式的控制条问题

### ISSUE THREAD

**Issue by chinabattlehawk** [Chimeejs/chimee-mobile-player#15]
你好，在移动端使用版本为 v0.2.1 的 chimee-mobile-player.browser，但是将资源为 m3u8 的实例配置了 isLive: true 后，播放时，控制条是这样的：
![123](https://user-images.githubusercontent.com/29477870/39035786-df04f07c-44ad-11e8-9c65-37a650e51eae.jpg)
请问这里怎么设置才好？

**Comment by chinabattlehawk** [comment]
plugin: [
			{
				name: 'chimeeMobiControlbar',
				majorColor: '#ffd000',
				hideBarTime: 2000,
				errorTips: '未在直播时间或资源不存在',
				children: {
					play: {},
					currentTime: {},
					progressBar: {},
					totalTime: {},
					screen: {
						event: {
							tap: setFull
						}
					}
				}
			}
另外问一下，那个 errorTips 的提示文字可以改吗？是在 plugin 中改吗？

**Comment by yandeqiang** [comment]
https://github.com/chimeejs/chimee-plugin-mobile-controlbar
https://github.com/chimeejs/chimee-plugin-mobile-state
这俩的 reademe 看下， 基本可以解答你的问题。
设置children 按照你的 children 来。  errortips 需要在 plugin 修改

**Comment by chinabattlehawk** [comment]
看到了，多谢多谢！
