### ISSUE TITLE
ios打包后的APP全屏后显示原生控件

### ISSUE THREAD

**Issue by aoilti** [Chimeejs/chimee-mobile-player#16]
Q: 使用cordova将chimee打包进APP后，在播放调用的时，ios全屏状态下无法屏蔽原生控件

UA信息：`Mozilla/5.0 (iPhone; CPU iPhone OS 11_1_1 like Mac OS X) AppleWebKit/604.3.5 (KHTML, like Gecko) Mobile/15B150 (4306536368)`

配置项：
```
{
    wrapper: "#wrap-video", 
    src: url,
    autoplay: false,
    controls: true,
    playsInline: true,
    preload: true,
    x5VideoPlayerFullscreen: false,
    x5VideoOrientation: "landscape",
    xWebkitAirplay: true,
    muted: false
}
```
展示效果：
![image](https://user-images.githubusercontent.com/19969080/39189296-780ab0be-4804-11e8-8010-87dd8d3e2d53.png)
![image](https://user-images.githubusercontent.com/19969080/39189324-8fa602aa-4804-11e8-8885-2efb29fafada.png)

**Comment by toxic-johann** [comment]
可以尝试使用[ css 全屏的方法](https://github.com/toxic-johann/es-fullscreen#usestylefirst) 代替么？

在引入 chimee 前加入如下代码。

```javascript
import esFullscreen from 'es-fullscreen';

esFullscreen.useStyleFirst = true;
```

在接下来的小版本我们会考虑在 chimee 上开放这个配置项。

在以后我们会引入 canvas 来解决这种机型不统一的问题。

**Comment by toxic-johann** [comment]
如果 playsinline 生效的话应该不需要使用 `esFullscreen` 设置样式全屏，全屏可以直接生效的。

**Comment by toxic-johann** [comment]
如果使用的是 chimee ，可以下载 chimee 的 alpha 版本来配置。详细配置方法见链接： https://github.com/Chimeejs/chimee/releases/tag/0.10.0-alpha.4

**Comment by zyg-github** [comment]
搭个车 问题个问题 
在 wkwebview（已经设置了allowsInlineMediaPlayback = YES） 上用 chimee-mobile-player 可以内联播放 但是点击全屏播放 控制调不显示 
<img src="http://7xj3hw.com1.z0.glb.clouddn.com/vedio-test.jpg">

**Comment by Zhang1051127659** [comment]
兄dei，贴一下设置。config.xml的和你初始化播放器的，还有你出问题的机型

**Comment by zyg-github** [comment]
var player = new ChimeeMobilePlayer({
  wrapper: '#wrapper',  // video dom容器
  src: './venom.mov',
  controls: true,
  playsInline: true,
  preload: true,
});
没有config.xml 是原生的 wkwebview
模拟器 ios11 iphonex

**Comment by zyg-github** [comment]
@Zhang1051127659  全屏是全屏了 不过 没有控制条而已

**Comment by Zhang1051127659** [comment]
@zyg-github 老铁，这个恕我没能复现出来。我在真机调试和模拟器调试都是可以的。

**Comment by zyg-github** [comment]
@Zhang1051127659  找到问题了 是客户端的锅 
打扰了 谢谢
