### ISSUE TITLE
如何点击正在播放的屏幕，视频暂停播放？

### ISSUE THREAD

**Issue by bozomoyy** [Chimeejs/chimee-mobile-player#17]
如题，似乎没有响应的参数可设置

**Comment by yandeqiang** [comment]
参考了其他厂商的一个操作流程是：
暂停的情况， 可以点击屏幕开始播放
播放的情况，只能点击控制条来暂停播放，
如果你要这种操作 可以看这个，https://github.com/chimeejs/chimee-plugin-mobile-state 的`state-tap` 事件来操作 player 的播放。

**Comment by bozomoyy** [comment]
好的，多谢作者贡献那么好的插件
