### ISSUE TITLE
请问如何监听播放器事件

### ISSUE THREAD

**Issue by chinabattlehawk** [Chimeejs/chimee-mobile-player#18]
oPlayer.addEventListener('canplay', function () {
	console.log('can');
	oVideoObj.videoErrImg.style.display = 'none';
});
没有效果；

含义：绑定事件监听
别名：addEventListener
参数：
key
类型：string
含义：事件名称
fn
类型：Function
含义：处理函数
利用 on 可以直接监听任何发生在 video 上的事件。

但是 video 只是 chimee 上的一部分。chimes 分为 wrapper, container, video 三个层级。

如果要监听 wrapper 上的事件，请添加前缀 w_

如果要监听 container 上的事件，请添加前缀 c_

要理解 chimee 的事件体系，请阅读《为什么要将 Chimee 设计成一个组件化框架？》中的事件体系部分。

上面的链接已失效，并且给什么加前缀也不是很清楚。
chimee-mobile-player v0.2.1

**Comment by chinabattlehawk** [comment]
另外还想请问一下，如果视频地址无效，会尝试连接多久才会停止？为什么那个等待的菊花一直在转？

**Comment by yandeqiang** [comment]
loading 那个是 30s. 可以自定义时间 https://github.com/chimeejs/chimee-plugin-mobile-state

**Comment by toxic-johann** [comment]
canplay 事件没有触发么？请问使用的依赖和版本是？

**Comment by chinabattlehawk** [comment]
你好，是的，没有触发，使用的是：chimee-mobile-player.browser.js，版本是：chimee-mobile-player v0.2.1。
另外 yandeqiang 老师说的 loading 时间没有起作用，所以还想请教一下，有没有手动中止加载视频源的方法？比如我想设置从加载开始，10秒内，不管视频源是否有效，我都停止加载？
感谢感谢！

**Comment by toxic-johann** [comment]
通过这个 [demo](https://github.com/Chimeejs/chimee/tree/master/demo/chimee-mobile-player) 测试没有复现这个问题喔。
