### ISSUE TITLE
【建议】针对没有babel项目引入chimee的建议

### ISSUE THREAD

**Issue by Zhang1051127659** [Chimeejs/chimee-mobile-player#19]
建议对于没有使用babel的项目引入chimee时不要直接引入`<script src='./lib/chimee-mobile-player.browser.js'></script>`

我在使用chimee-mobile-player时直接查看文档看到文档中安装部分说:
`首先根据您的业务场景，你可以直接将lib目录下适合的打包文件引入您的业务代码中，比如直接使用<script src='./lib/chimee-mobile-player.browser.js'></script>引用JS。`

一时懵逼就按照这样的方式引用了，后来发现在低版本的安卓手机上点击屏幕部分会报`undefined is not a function `的错误，经过排查后发现是因为在`chimee-mobile-player.browser.js`的第12139行使用了数组的indexof方法判断当前点击元素是不是包含`chimee-state-play`这个节点，由于indexof是ES6语法，所以导致了上述错误。

另外针对两个元素的包含关系的判断建议使用`node.contains()`这个方法。

**Comment by Zhang1051127659** [comment]
刚刚我尝试引入了`./lib/chimee-mobile-player.browser.min.js`文件，发现依然解决不了报错的问题，而后我又尝试在babel官网上复制了一下`chimee-mobile-player.browse.js`源码，发现对于数组的`Array.prototype.indexOf`方法不能babel转换，经过这个过程我觉得这应该是一个bug，或者是说针对chimee播放器，这是由于API问题导致的兼容问题。

**Comment by Zhang1051127659** [comment]
好吧，我又瞎叭叭了。
`Array.prototype.indexOf`是ES5里添加的，我还是贴上我的错误详细信息吧。

UA: `Mozilla/5.0 (Linux; Android 5.0.2; CHE-TL00H Build/HonorCHE-TL00H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36`

机型：华为，魅族等安卓版本比较低的手机

**Comment by yandeqiang** [comment]
这个属性确实是 es5 得。 babel 不会转这个。 那就引入 babel-polyfill 吧。我改下文档。
