### ISSUE TITLE
在安卓微信上同层播放器全屏的问题？

### ISSUE THREAD

**Issue by dujuncheng** [Chimeejs/chimee-mobile-player#2]
请问是否解决了在安卓微信上同层播放器全屏的问题？在dev.md 里面看到有涉及到x5videoexitfullscree，但是貌似在代码里面没有找到

**Comment by yandeqiang** [comment]
解决了同层播放的问题， 但是全屏问题， 据我的测试， x5videoexitfullscreen， 这个属性，没有起作用。https://github.com/yandeqiang/blog/issues/8 这里面有一些记录， 可以看看。

**Comment by dujuncheng** [comment]
恩恩，好的，多谢
