### ISSUE TITLE
请问ios上，全屏后视频不能随着手机转动而横屏播放吗？

### ISSUE THREAD

**Issue by lxh3811958** [Chimeejs/chimee-mobile-player#20]
如下图，全屏模式下只能这样显示，我应该怎么设置才能让它变成横屏模式
![_20180517160801](https://user-images.githubusercontent.com/17581529/40164601-9f59239a-59ec-11e8-8208-61be0447533c.jpg)

我的配置如下图
![1526544386 1](https://user-images.githubusercontent.com/17581529/40164627-abb694f6-59ec-11e8-8dce-92c93e86c786.jpg)

**Comment by toxic-johann** [comment]
暂时还没有做横屏模式的适配。如果有需求，需要利用 css 全屏实现。

建议可以下载 https://github.com/Chimeejs/chimee/releases/tag/0.10.0-alpha.4 这个版本或以上版本。按照所指示方法选择。然后再利用 transform 等属性实现。

或者等待我们进行相关的实现。可以在此提需求。https://github.com/Chimeejs/chimee/issues/119

**Comment by lxh3811958** [comment]
好的，谢谢

**Comment by toxic-johann** [comment]
@yandeqiang 顺便看看有没有其他建议。

**Comment by yandeqiang** [comment]
这块有个文档书写错误，x5VideoOrientation: landscape, protraint, landscape|portrait
可查看 https://x5.tencent.com/tbs/guide/video.html
