### ISSUE TITLE
在微信浏览器中，安卓手机视频播放控件设置z-index无效

### ISSUE THREAD

**Issue by stonemakers** [Chimeejs/chimee-mobile-player#22]
在微信浏览器中，试了小米 MIX2s ， 乐视Pro3 都不行， 所有的安卓手机，视频都被置顶

**Comment by stonemakers** [comment]
@yandeqiang 按照方案里的说明，在初始化chimeeMobilePlayer的时候，添加一个 x5VideoPlayerType 属性就能自动添加 x5-video-player-type="h5" 属性。但是实际测试，组件初始化后，没有给video标签添加这个属性，怎么回事

**Comment by yandeqiang** [comment]
可以看下配置吗？ 你也可以对照这里看下 https://github.com/Chimeejs/chimee/blob/master/doc/zh-cn/api/plugin-api.md#videoconfig

**Comment by stonemakers** [comment]
@yandeqiang 
```
```
<template>
  <section class="x-video" :class="{suspend: isSuspend}">
    <div id="wrapper">
    </div>
  </section>
</template>
```
this.chimee = new ChimeeMobilePlayer({
        wrapper: '#wrapper',
        src: (我的视频地址),
        autoplay: false,
        controls: true,
        playsInline: true,
        preload: 'auto',
        x5VideoPlayerFullscreen: true,
        x5VideoPlayerType: 'h5',
        x5VideoOrientation: 'landscape|portrait',
        xWebkitAirplay: true,
        muted: true,
        // 使用插件
        plugin: [
          {
            name: chimeePluginMobileControlbar.name,
            majorColor: '#0076ff'
          }
        ]
      })
```

**Comment by yandeqiang** [comment]
@toxic-johann 这个属性值没有赋值上去 。 我看是有多次赋值。 除了第一次为 h5 , 剩下均为 undefined。 在 pc 上试的

**Comment by toxic-johann** [comment]
ok。今晚看看

**Comment by toxic-johann** [comment]
[chimee 0.10.5](https://github.com/Chimeejs/chimee/releases/tag/0.10.5) 已修复

**Comment by stonemakers** [comment]
@yandeqiang @toxic-johann 请问有修复chimee-mobile-player这个项目中的问题么？

**Comment by toxic-johann** [comment]
chimee-mobile-player @yandeqiang 同步升级即可。

**Comment by yandeqiang** [comment]
已更新 chimee-mobile-player@0.2.7 @stonemakers
