### ISSUE TITLE
js 体积太大，能否拆分直播和点播的js代码

### ISSUE THREAD

**Issue by ZooTopiaGG** [Chimeejs/chimee-mobile-player#23]
gzip都有100多kb 比我整个项目gizp都大

**Comment by songguangyu** [comment]
都使用了哪些模块？底层解码器代码主要在编码和解码上 点播和直播区分的代码量不多

**Comment by ZooTopiaGG** [comment]
我刚刚开始用 ，然后 用这个项目 写demo的时候 发现的  我用的场景就是点播，然后统一各手机端浏览器的样式问题，没注意模块，那么我应该使用哪些模块呢
