### ISSUE TITLE
wechat问题

### ISSUE THREAD

**Issue by webfrontzhifei** [Chimeejs/chimee-mobile-player#24]
window.WeixinJSBridge 以及WeixinJSBridge.invoke都已经不存在了吧。现在都是window.wx了

**Comment by yandeqiang** [comment]
刚在安卓机器上看了下， 目前这个版本 window.WeixinJSBridge 确实已经废弃掉了。
这个方法目前在 chimee-plugin-mobile-controlbar 中使用，主要是为了想要实现自动播放的功能，如果不支持该属性，则不支持该功能。不影响其他流程。
window.wx 得引入 https://res.wx.qq.com/open/js/jweixin-1.2.0.js 才可以使用吧。
