### ISSUE TITLE
内网无法安装依赖，求优雅的解决方案

### ISSUE THREAD

**Issue by AlbertKnag** [Chimeejs/chimee-mobile-player#25]
npm i chimee-mobile-player
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/Chimeejs/chimee-plugin-mobile-controlbar.git
npm ERR! 
npm ERR! fatal: unable to access 'https://github.com/Chimeejs/chimee-plugin-mobile-controlbar.git/': SSL connect error
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-27T03_45_02_021Z-debug.log

**Comment by toxic-johann** [comment]
尝试 cdn 下载吧 https://www.jsdelivr.com/package/npm/chimee-mobile-player
