### ISSUE TITLE
ios设备全屏播放无法横屏，必须打开旋转屏幕转动屏幕才可以

### ISSUE THREAD

**Issue by stonemakers** [Chimeejs/chimee-mobile-player#27]
``` javascript
this.chimee = new ChimeeMobilePlayer({
        wrapper: '#wrapper', // video dom容器
        src: url,
        isLive: true,
        width: this.width,
        height: this.height,
        autoplay: false,
        controls: true,
        playsInline: true,
        preload: true,
        x5VideoPlayerFullscreen: false,
        x5VideoOrientation: 'landscape',
        xWebkitAirplay: true,
        muted: false,
        poster: this.poster
        // removeInnerPlugins: ['chimeeMobiControlbar', 'chimeeState'] // 需要移除的插件
      })
```

**Comment by yandeqiang** [comment]
这块你可以自己 transform 下。 但是要判断， 屏幕的当时方向。

**Comment by yandeqiang** [comment]
你这个 evt.target 是那个 wrapper 吗？

**Comment by stonemakers** [comment]
@yandeqiang 那个是外层的container元素 ，我即便换成document.getElementById('wrapper') 也不行

**Comment by yandeqiang** [comment]
旋转 video 元素。 说错了。 

`videoElement.style = 'transform: rotate(90deg); '` 

这块你调整 video 的宽高/角度。 就好了。

**Comment by stonemakers** [comment]
![wechatimg107](https://user-images.githubusercontent.com/17716867/44327242-9feaa100-a490-11e8-9183-04366c56a028.jpeg)
进度条也要旋转么

**Comment by stonemakers** [comment]
@yandeqiang 我发现这样旋转后，定位也是个麻烦事儿

**Comment by stonemakers** [comment]
@yandeqiang @welefen

**Comment by yandeqiang** [comment]
找了几篇移动端强制横屏的方式，大多是也都是 transform 然后 js 控制位置方式。 这块你先可以外部控制。我这块。 想想怎么整体协调。
这块目前需要 absolute 的插件，需要 js 去算相对的位置。 @toxic-johann 这边有什么比较好的方式吗？

**Comment by 617481349** [comment]
> 找了几篇移动端强制横屏的方式，大多是也都是 transform 然后 js 控制位置方式。 这块你先可以外部控制。我这块。 想想怎么整体协调。
> 这块目前需要 absolute 的插件，需要 js 去算相对的位置。 @toxic-johann 这边有什么比较好的方式吗？

即使旋转了，样式也没问题，但是进度条的拖动响应是有问题的
