### ISSUE TITLE
ios 10下的微信内没法播放

### ISSUE THREAD

**Issue by limingyang2012** [Chimeejs/chimee-mobile-player#28]
您好，非常感谢提供这么好的播放器。

我在使用的时候将自带的插件都移除后removeInnerPlugins: ['chimeeMobiControlbar', 'chimeeState']。

在iphoneX上表现的非常好，在安卓手机上表现也很好。但是测试了两台ios 10上没法播放，只能看见poster图片，看不到任何可点击播放的按钮，点击poster也没有办法进行播放。

如果只移除chimeeMobiControlbar的话，会出现chimeeState提供的播放按钮，但是由于这个是全屏的，造成了没有办法去点击原生提供的播放控件，不知道有啥好的办法么，还是需要自己撸插件。

**Comment by yandeqiang** [comment]
看下配置

**Comment by limingyang2012** [comment]
![image](https://user-images.githubusercontent.com/10152413/44440892-bf064180-a5fc-11e8-80ac-3051abd2a025.png)
是我的配置么，我这边写 的很简单。

**Comment by limingyang2012** [comment]
![image](https://user-images.githubusercontent.com/10152413/44440923-e65d0e80-a5fc-11e8-8178-48b6fe1c658e.png)
我这边的配置么，现在写的很简单。后面移除插件的那个现在给删掉了。

**Comment by yandeqiang** [comment]
你的核心问题是， 在 ios 10 上 原生的控制条没有出来，是吗 ？

**Comment by limingyang2012** [comment]
对的。插件都移除后，ios10上只能看见展示了poster，没法控制播放。

**Comment by yandeqiang** [comment]
你看页面上 video 标签是否有 controls 选项。 如果有的话， 直接试试用原声 video 来看看。 如果没有的话， 可以直接使用chimee [模块](http://github.com/chimeejs/chimee) new Chimee 一下。

**Comment by limingyang2012** [comment]
好的，我看下。

**Comment by limingyang2012** [comment]
您好，您指的new Chimee是指将移动端的那个换成这个是么

**Comment by yandeqiang** [comment]
嗯。 你看下那个模块怎么用。 和这个类似的。 我这个底层基于他。如果你不考虑用插件的话， 可以直接使用。

**Comment by limingyang2012** [comment]
好，我试试

**Comment by limingyang2012** [comment]
现在问题就比较严重了，我用了Chimee这个在有问题的手机上微信内依然没法播放，在同手机safari上可以播放。换成原生video情况是一样的，很忧伤。

**Comment by yandeqiang** [comment]
[惊恐]， video 原生无法用？ 先去掉 poster ? 不要任何参数， 只要 src
