### ISSUE TITLE
点击播放进度条，调整播放进度存在偏差

### ISSUE THREAD

**Issue by 617481349** [Chimeejs/chimee-mobile-player#29]
当给chimee绑定的实例容器,的父盒子添加padding属性，使实例容器缩小时，点击播放进度条，调整播放进度时存在偏差，这个偏差值与父盒子添加的padding值有关联

**Comment by yandeqiang** [comment]
里面都是 100% 所以会造成影响， 他要在 wrapper 设置 padding。 你看下 container 的宽高。 然后设置为具体值。 不要百分比。 问题来源是这个。

**Comment by 617481349** [comment]
`<template>
    <div id="test">
        <div id="wrapper"></div>
    </div>
</template>

<script>
import ChimeeMobilePlayer from 'chimee-mobile-player'
import chimeePluginMobileControlbar from 'chimee-plugin-mobile-controlbar'
export default {
    data() {
        return {
            Chimee: ''
        }
    },
    mounted() {
        ChimeeMobilePlayer.install(chimeePluginMobileControlbar)

        this.Chimee = new ChimeeMobilePlayer({
            wrapper: '#wrapper', // video dom容器
            src: 'http://chimee.org/vod/1.mp4',
            autoplay: false,
            controls: true,
            playsInline: true,
            preload: true,
            x5VideoPlayerFullscreen: true,
            x5VideoOrientation: true,
            xWebkitAirplay: true,
            muted: true,
            plugin: [
                {
                    name: chimeePluginMobileControlbar.name,
                    children: {
                        play: true,
                        currentTime: true,
                        totalTime: true,
                        progressBar: true,
                        screen: true
                    }
                }
            ]
        })
    },
    created() {}
}
</script>

<style scoped lang="scss">
#test{
  padding: 15px;
}
#wrapper {
  width: 345px !important;
}
</style>
<style>
@import "chimee-mobile-player/lib/chimee-mobile-player.browser.css";
chimee-control {
  font-size: 0.24rem;
}
container {
  width: 345px !important;
}
</style>
`
我已经尝试着将container设置为具体的宽度，但并没能解决这个问题

**Comment by 617481349** [comment]
![image](https://user-images.githubusercontent.com/26165405/44573073-421fc700-a7b8-11e8-930b-44e913b76bcb.png)
这是我的代码,我已经尝试着通过样式将wrapper ，与container 的宽都设置为具体的宽度，但并没能解决这问题
