### ISSUE TITLE
嵌入到安卓APP中，有的机型有报错。

### ISSUE THREAD

**Issue by chinabattlehawk** [Chimeejs/chimee-mobile-player#3]
例如小米6，华为P9，点击一个按钮，将播放器的src变更后，不能播放，自动播放已开，调用play()方法也无效。播放器的遮罩层的播放按钮会显示，点击的话，在AndriodStudio中会报错（在Chrome上调试并不会，也能正常播放，一切都很祥和）：
01-17 16:38:23.490 31165-31165/cn.xxx.shapp I/chromium: [INFO:CONSOLE(4981)] "Uncaught (in promise) NotSupportedError: The element has no supported sources.", source: http://media.xxx.cn/live/lib/chimee/chimee-mobile-player.browser.js (4981)
希望你们能看到，谢谢。

**Comment by yandeqiang** [comment]
这个是在 安卓客户端？

**Comment by toxic-johann** [comment]
具体是什么浏览器呢？还是说自己封装的安卓客户端？有更详细的报错信息吗？

**Comment by chinabattlehawk** [comment]
是安卓调取H5的页面：
功能正常的浏览器信息：
华为 mate7：
![mate7](https://user-images.githubusercontent.com/29477870/35078867-561d6944-fc3f-11e7-9489-0b2fd30c8b17.jpg)
魅族 Pro5：
![pro5](https://user-images.githubusercontent.com/29477870/35078873-64c07086-fc3f-11e7-8ea2-f975cfb6aa6e.jpg)
华为 P8 Max：
![p8 max](https://user-images.githubusercontent.com/29477870/35078877-6f3a8128-fc3f-11e7-962c-92618aa660a0.jpg)
功能异常并报错的浏览器信息：
三星 S8+：
![s8](https://user-images.githubusercontent.com/29477870/35078899-88ca0078-fc3f-11e7-8efc-a18e4a33d18e.jpg)
华为 P9：
![p9](https://user-images.githubusercontent.com/29477870/35078905-9167ce68-fc3f-11e7-9e73-8acb8a40b5d7.jpg)
以及暂时没办法截图的小米6……
麻烦你们了。

**Comment by songguangyu** [comment]
测试的视频资源发一下。
