### ISSUE TITLE
Uncaught (in promise) DOMException: The element has no supported sources.

### ISSUE THREAD

**Issue by shen-lan** [Chimeejs/chimee-mobile-player#34]
做的是直播。直接复制的demo代码。流地址
```http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8```
真机上测试播放没问题。但是pc端，chrome 模拟手机会出现这个错误。
```Uncaught (in promise) DOMException: The element has no supported sources.```
1. 那么问题来了，我该怎么在本地调试..... 
2. 看文档监听事件的部分，似乎都是‘’ video 上的 dom 事件，如 click ，target 为 'video-dom'‘’，这样的点击事件。 以这个报错为例，请问如何去监听播放成功或者播放失败事件？
谢谢大佬

**Comment by shen-lan** [comment]
```
       <section id="wrapper" class="chimee-container">
            <video tabindex="-1"></video>
        </section>
    <script>
        var livePalyer = new ChimeeMobilePlayer({
                wrapper: '#wrapper',  // video dom容器
                src: 'http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8',
                isLive: true,
                autoplay: true,
                controls: false,
                playsInline: true,
                preload: 'auto',
                x5VideoPlayerFullscreen: true,
                x5VideoOrientation: 'landscape|portrait',
                xWebkitAirplay: true,
                muted: true,
                disableUA: ['Mozilla/5.0 (Linux; Android 4.4.2; HM NOTE 1TD Build/KOT49H; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.97 Mobile Safari/537.36']
            });
            livePalyer.on('error', evt => alert(111));
    </script>
```

以上是代码。
这个事件是原生的视频video吗？写了并没有生效.....

**Comment by toxic-johann** [comment]
事件直接使用 liveplayer.on 这种来使用

**Comment by toxic-johann** [comment]
chrome 上面可能需要安装一个 m3u8 kernel。

**Comment by shen-lan** [comment]
```https://github.com/Chimeejs/chimee-kernel-hls```
下载到本地 引用lib里的index，
配置
 ``` kernels: {
    hls: ChimeeKernelHls,
  }```
依然有这个错误.....

**Comment by toxic-johann** [comment]
用的什么版本

**Comment by toxic-johann** [comment]
https://codepen.io/toxic-johann/pen/eQgBVW?editors=1111  貌似没有遇到这个问题。。。只是视频源播放不出来。。。

**Comment by shen-lan** [comment]
> https://codepen.io/toxic-johann/pen/eQgBVW?editors=1111 貌似没有遇到这个问题。。。只是视频源播放不出来。。。
用的是最新版本。
您试下点击播放，F12看一下，其实也是报了一样的错误的......
```Uncaught (in promise) DOMException: The element has no supported sources```
实在不行就算了....只是调试不了而已，放到真机上确实是可以播的。
斗鱼虎牙的hls直播在PC端模拟手机也是看不了的，真机可以。
谢谢您的热心解答
