### ISSUE TITLE
给的demo下载下来播放不了，也不报错，是什么原因呀？

### ISSUE THREAD

**Issue by cc0822** [Chimeejs/chimee-mobile-player#35]

**Comment by toxic-johann** [comment]
请问是在哪里下载呢？

**Comment by cc0822** [comment]
chimee-mobile-player这个文件里面有个demo文件夹，我看里面是作者写的一个例子，但是我跑起来，页面出来了，但是视频播放不了，也没报错

**Comment by toxic-johann** [comment]
你直接 clone 的 GitHub 么

**Comment by cc0822** [comment]
恩恩，是的

**Comment by toxic-johann** [comment]
@yandeqiang 回答一下～

**Comment by yandeqiang** [comment]
http://draft.yandeqiang.com/chimee-mobile-player/demo/ 这个地址试着模仿一下？ 可以不？ 播放不了是指， 点了播放按钮之后也没有反应？ 还是一开始不能自动播放？
