### ISSUE TITLE
关于直播源绑定之后，立刻点击播放，加载源会特别慢

### ISSUE THREAD

**Issue by dengweijing** [Chimeejs/chimee-mobile-player#36]
由于是提前将播放源拿到，我跳转到视频播放页面，初始化video标签，发现立刻点击播放，加载源总是会很慢，但是如果等待1s再点击播放，这种方式便会很快播放，刚开始我以为是初始化的问题，但是实际测试不是。

**Comment by HanasakiDeng** [comment]
.m3u8文件，是开发在政务微信内的小程序 ，政务微信版本1.5.1

**Comment by toxic-johann** [comment]
hmmm。没用过政务微信。不过一般 m3u8 在移动端都可以原生播放。可以先简单使用一个普通网页检验。

**Comment by HanasakiDeng** [comment]
好的， 我尝试下，谢谢啦
