### ISSUE TITLE
集成的移动端播放器怎么修改控制条UI？

### ISSUE THREAD

**Issue by tracyxu5298** [Chimeejs/chimee-mobile-player#37]
如题： 文档中未找到在集成里面的相关说明

**Comment by yandeqiang** [comment]
https://github.com/chimeejs/chimee-plugin-mobile-controlbar 看下这里 readme. 

```js
plugin: [{
  name: chimeePluginMobileControlbar.name,
  majorColor: '',
  hoverColor: '',
  children: {

  }
}]
```

**Comment by tracyxu5298** [comment]
> https://github.com/chimeejs/chimee-plugin-mobile-controlbar 看下这里 readme.
> 
> ```js
> plugin: [{
>   name: chimeePluginMobileControlbar.name,
>   majorColor: '',
>   hoverColor: '',
>   children: {
> 
>   }
> }]
> ```



> https://github.com/chimeejs/chimee-plugin-mobile-controlbar 看下这里 readme.
> 
> ```js
> plugin: [{
>   name: chimeePluginMobileControlbar.name,
>   majorColor: '',
>   hoverColor: '',
>   children: {
> 
>   }
> }]
> ```

这边改动的是整个UI颜色，如何区分进度条和 播放按钮的颜色设置

**Comment by tracyxu5298** [comment]
这个配置，配置的是整个UI的颜色等， 如何区分播放按钮和 进度条呢

**Comment by tracyxu5298** [comment]
如何区分进度条和播放按钮的UI呢，我想给他们配置不同的颜色，看了后面的配置，并没有单独区分配置UI的颜色
