### ISSUE TITLE
是否支持ios?

### ISSUE THREAD

**Issue by h371535926** [Chimeejs/chimee-mobile-player#4]
是否支持ios?

**Comment by toxic-johann** [comment]
支持呀。

**Comment by toxic-johann** [comment]
具体问什么特性呢？

**Comment by yandeqiang** [comment]
是在 app 里还是在 web 页面中使用？

**Comment by h371535926** [comment]
webview。flv格式

**Comment by toxic-johann** [comment]
https://github.com/yandeqiang/blog/issues/8  flv 在移动端兼容性非常差。建议不要使用该格式。

**Comment by yandeqiang** [comment]
webview 的话， 还需要客户端来配合设置， playsinline / autoplay 等参数。 具体参考下各家 webview 相关文档

**Comment by songguangyu** [comment]
移动端建议使用mp4格式进行点播，hls（m3u8）进行直播。

**Comment by niceMoonMaker** [comment]
> Refere

大佬，为什么我在苹果的微信小程序打开webview后，还是不能播放？

**Comment by niceMoonMaker** [comment]
> > Refere
> 
> 大佬，为什么我在苹果的微信小程序打开webview后，还是不能播放？
https://www.xiniantech.com.cn/jingtai-health/sys/common/view//wxAppImg/video/e2591ac4fd62723d02249cd67af708d.png
