### ISSUE TITLE
ios点击全屏按钮，如何调起默认自定义全屏

### ISSUE THREAD

**Issue by ZIoving** [Chimeejs/chimee-mobile-player#40]

**Comment by toxic-johann** [comment]
hmm。不是很懂描述的什么意思。

**Comment by ZIoving** [comment]
![image](https://user-images.githubusercontent.com/18425402/50626033-dc61f980-0f66-11e9-9cce-71f4cdb1149e.png)
正常播放需要playsinline，点击screen，想调用ios默认的全屏
![image](https://user-images.githubusercontent.com/18425402/50626122-5b573200-0f67-11e9-880a-c0c5218ccf70.png)

**Comment by ZIoving** [comment]
需求很怪异。。 点击全屏 需要展示这样的效果
![image](https://user-images.githubusercontent.com/18425402/50626170-a96c3580-0f67-11e9-81ab-19ffa1cc2cc9.png)

**Comment by ZIoving** [comment]
![image](https://user-images.githubusercontent.com/18425402/50626178-b6892480-0f67-11e9-8b4a-e0931fced6ad.png)

**Comment by ZIoving** [comment]
点击screen之后希望展示
![image](https://user-images.githubusercontent.com/18425402/50626220-f7813900-0f67-11e9-8e04-37ff6176eb4d.png)

**Comment by toxic-johann** [comment]
看了看应该是移动端默认调用了 css 全屏。可以参考这个设置把 css 全屏关掉试试。https://github.com/Chimeejs/chimee/blob/99f87d9aaa5599e6b3529d7f9f5f5d497142bf82/doc/zh-cn/api/chimee-api.md#usestylefullscreen
