### ISSUE TITLE
苹果部分机型不能播放

### ISSUE THREAD

**Issue by Cpaul3** [Chimeejs/chimee-mobile-player#45]
苹果部分机型不能播放（iPhoneX iPhone8P iPhone6s）.点击播放按钮报错Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.改成静音自动播放也不行。大神，帮忙看一下

**Comment by toxic-johann** [comment]
https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

**Comment by toxic-johann** [comment]
safari 播放策略的问题。建议可以在收到 error 后弹出 ui 让用户处理。

**Comment by Cpaul3** [comment]
感谢，问题的原因找到了，好像是ios12以上的版本，开启低电量模式，请求被系统給拒绝了。您有遇到过这种情况吗？

**Comment by toxic-johann** [comment]
哦。。。居然做了这种优化。没有遇到过。不过你们可以针对性做一下逻辑。

**Comment by Cpaul3** [comment]
是针对低电量模式下做一下处理吗？我们是ionic混合开发的，有点难。您有没有什么高见？



------------------ 原始邮件 ------------------
发件人: "Heng Zhong"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 下午3:54
收件人: "Chimeejs/chimee-mobile-player"<chimee-mobile-player@noreply.github.com>; 
抄送: "段盼盼"<1136844228@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Chimeejs/chimee-mobile-player] 苹果部分机型不能播放 (#45)




哦。。。居然做了这种优化。没有遇到过。不过你们可以针对性做一下逻辑。

**Comment by toxic-johann** [comment]
不是。针对这个报错，返回到 pause 状态让用户自己手动触发就好了。

**Comment by Cpaul3** [comment]
我使用try catch 捕获不到这个错误，我们不是自动播放的，是用户收到点击控制条的播放按钮，手动控制的。
我新增播放按钮，让用户手动触发，但请求还是被拦截。




------------------ 原始邮件 ------------------
发件人: "Heng Zhong"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 下午3:58
收件人: "Chimeejs/chimee-mobile-player"<chimee-mobile-player@noreply.github.com>; 
抄送: "段盼盼"<1136844228@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Chimeejs/chimee-mobile-player] 苹果部分机型不能播放 (#45)




不是。针对这个报错，返回到 pause 状态让用户自己手动触发就好了。

**Comment by toxic-johann** [comment]
你试试 player.$video.play() 能不能播放。我怀疑是因为 chimee 内部会走入异步的问题。

**Comment by Cpaul3** [comment]
刚刚试了不行，我用H5 video标签试了也同样报错。但是在Safire中可以，会不会跟我们的打包有关系。之前也问过ios开发，他们没有出现过这个问题。



------------------ 原始邮件 ------------------
发件人: "Heng Zhong"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 下午4:12
收件人: "Chimeejs/chimee-mobile-player"<chimee-mobile-player@noreply.github.com>; 
抄送: "段盼盼"<1136844228@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Chimeejs/chimee-mobile-player] 苹果部分机型不能播放 (#45)




你试试 player.$video.play() 能不能播放。我怀疑是因为 chimee 内部会走入异步的问题。

**Comment by toxic-johann** [comment]
额。你是说在 safari 中 chimee 和 video 都是正常的吗？那可能还是需要调试一下你们 app。具体要和他们商量下了。最好先用 video 确认下呗。

**Comment by Cpaul3** [comment]
好的，谢谢



------------------ 原始邮件 ------------------
发件人: "Heng Zhong"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 下午4:46
收件人: "Chimeejs/chimee-mobile-player"<chimee-mobile-player@noreply.github.com>; 
抄送: "段盼盼"<1136844228@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Chimeejs/chimee-mobile-player] 苹果部分机型不能播放 (#45)




额。你是说在 safari 中 chimee 和 video 都是正常的吗？那可能还是需要调试一下你们 app。具体要和他们商量下了。最好先用 video 确认下呗。
