### ISSUE TITLE
一些属性无法透传到video上

### ISSUE THREAD

**Issue by mraiguo** [Chimeejs/chimee-mobile-player#54]
看了一下文档提供的这些属性：https://chimee.org/docs/chimee_api.html#video%E5%85%83%E7%B4%A0%E7%9B%B8%E5%85%B3%E5%B1%9E%E6%80%A7，但是比如说我想给video传一些自定的属性。甚至不是自定义的，传入一个controlsList: 'nodownload'，让chrome控制条不显示下载按钮都不行。
    建议能不能将用户传入的不在api文档的属性给透传到video上。

**Comment by toxic-johann** [comment]
https://chimee.org/docs/chimee_api.html#videorequiredguardedattributes%EF%BC%88v0.10.0-%E5%90%8E%EF%BC%89 使用这个属性试试，你可以直接拿到 video 本身，注入你需要的属性。同时告知我们不要移除这些属性即可。

**Comment by mraiguo** [comment]
> https://chimee.org/docs/chimee_api.html#videorequiredguardedattributes%EF%BC%88v0.10.0-%E5%90%8E%EF%BC%89 使用这个属性试试，你可以直接拿到 video 本身，注入你需要的属性。同时告知我们不要移除这些属性即可。

目前是用了  `player.$video.controlsList = 'nodownload'` 处理
