### ISSUE TITLE
npm install安装不了啊，一直卡住。

### ISSUE THREAD

**Issue by basejs** [Chimeejs/chimee-mobile-player#58]
如题。

**Comment by leenannan** [comment]
我也是同样的问题 yarn add下载报错
![image](https://user-images.githubusercontent.com/24207713/82186907-29f1c300-991e-11ea-9268-6440ff518fd6.png)

**Comment by SteveChensong** [comment]
这个应该不维护了吧

**Comment by toxic-johann** [comment]
`npm install` 不通的原因是这个库依赖了 github 的源。欢迎 pr 修复。

**Comment by hongguilong** [comment]
"pluginConfig do not match requirement"

根据官网的案例，一直提示插件配置有问题

**Comment by yibingxiong** [comment]
> `npm install` 不通的原因是这个库依赖了 github 的源。欢迎 pr 修复。

已修复并自测通过， 请大佬过目~

[https://github.com/Chimeejs/chimee-mobile-player/pull/65](https://github.com/Chimeejs/chimee-mobile-player/pull/65)
