### ISSUE TITLE
https://s5.ssl.qhres.com/static/588b46b97caa0749.js 请求不到

### ISSUE THREAD

**Issue by Zian502** [Chimeejs/chimee-mobile-player#72]
![image](https://github.com/Chimeejs/chimee-mobile-player/assets/26033663/af43ea9f-7676-40df-b53a-994f4cffe8b3)
这个 js 是干嘛的，请求不到

**Comment by huzunjie** [comment]
是 VConsole 可以用 https://s5.ssl.qhimg.com/static/588b46b97caa0749.js 替换
