### ISSUE TITLE
安卓浏览器video无法使用自定义控制栏

### ISSUE THREAD

**Issue by wuzhenwen** [Chimeejs/chimee-mobile-player#8]
问大佬几个问题，也是这个插件没有解决的。
1、在安卓浏览器中，系统自带浏览器、UC、QQ等浏览器都无法使用自定义的控制栏，video播放都会由浏览器接管，使用浏览器的播放器样式。请问这个问题有解吗？
2、为了去除播放按钮等除了通过改变video的影子dom样式，还有其他方法没，因为这个在安卓浏览器不生效。
3、看腾讯的视频js可以实现所有浏览器统一使用自定义样式，究竟是怎么做到的呢。莫不会是因为腾讯和浏览器厂商有合作吧。。
大佬可以指点一下吗，感激不尽～
腾讯demo链接：http://m.v.qq.com/tvp/a_double_video_one_page.html

**Comment by yandeqiang** [comment]
被各个浏览器接管的问题就得找各个浏览器开白名单解决了。。。 目前没有什么好的方法
移动端被各个浏览器搞的很乱。。。
