### ISSUE TITLE
[bug report]android chrome can't load video when the box type is 'native'

### ISSUE THREAD

**Issue by shawerestart** [Chimeejs/chimee-mobile-player#9]
html: 
`<div class="preview-video">`
`     <div class="paddinger" @click="setPreviewVideoShow"></div>`
 `       <div id="PreviewVideo"></div>`
  `      <div class="paddinger" @click="setPreviewVideoShow"></div>`
    `</div>`

js:
` let player = new ChimeeMobilePlayer({`
                `wrapper: '#PreviewVideo',  // video dom容器`
                `src: 'xxxxxxx.mp4',`
                `// kernels: [],`
                `box: 'native',`
                `isLive: false,`
                `autoplay: true,`
                `controls: true,`
               ` playsInline: true,`
                `preload: true,`
                `x5VideoPlayerFullscreen: true,`
                `x5VideoOrientation: 'portrait',`
                `xWebkitAirplay: true,`
                `muted: false,`
                `crossOrigin: true`
            `})`
            `player.play()`

issue: 
 if i set the box attribute = 'native', the video can't play
 if i set the box attribute = 'mp4' the video can play

**Comment by yandeqiang** [comment]
http://draft.yandeqiang.com/chimee-mobile-player/demo/ 我在这试了 'native' ，没复现， 你可以看看， 你那效果
